### ISSUE TITLE
Assignment requirements (view.js/job.js)

### ISSUE THREAD

**Issue by tetsaiga86** [codefellows/seattle-301d4#11]
### What is the expected result?

The day 07 requirements give slightly contradictory requirements, that I am unsure how to work around: "Enclose the contents of each script file in an IIFE, that exports your high-level objects" and a tech requirement of "IIFE present on at least one .js file". So my first question is do I need an IFFE on both my js files?
### What is the actual result? 
  
The problem with putting an IFFE on both is that my functions can't be called between the two.

### If there is an error message, what is the error message?  
_ex: Uncaught Reference Error: $ is not defined._

### What steps have you taken to address the problem? 

I currently have it organized it so that I only have an IFFE on view.js, but again I'm not if that is what is wanted/required

## Please check these boxes _**after**_ clicking "Submit new issue":
- [x] I have entered the filename and the high-level problem as the title of this issue.
- [x] I have answered all four of the above questions, and have ensured that the **Preview** tab looks good.
- [x] I have not been able to work through the issue after 15 minutes.

**Comment by patci** [comment]
Hi Kyle! One file is great, two even better 😃 

I'll clear up this discrepancy.
