### ISSUE TITLE
Lecture slides missing

### ISSUE THREAD

**Issue by damoores** [codefellows/seattle-301d4#8]
### What is the expected result?
View lecture slides

### What is the actual result? 
I don't see the lecture slides

### If there is an error message, what is the error message?  
NONE

### What steps have you taken to address the problem? 

1. First I...double checked for lecture slides
1. Then I...checked in the codefellows-seattle.... repo for lecture slides and did not see them there

## Please check these boxes _**after**_ clicking "Submit new issue":
- [x ] I have entered the filename and the high-level problem as the title of this issue.
- [x ] I have answered all four of the above questions, and have ensured that the **Preview** tab looks good.
- [x ] I have not been able to work through the issue after 15 minutes.

**Comment by patci** [comment]
Resolved! Thanks 😄
